### ISSUE TITLE
Not support Thai and Lao language

### ISSUE THREAD

**Issue by savandev17** [andresperezmelo/print_bluetooth_termal#1]
This is awesome plugin, Please make it to support (Thai and Lao) languages sir.

Thanks in advance

**Comment by andresperezmelo** [comment]
I am going to do an investigation on whether the same commands to activate Chinese characters work for the Thai language, I do not know what commands are sent to the printer.

### In a few days I will return to report my achievements on this

## Tasks

- [ ] Investigate the command to enable Thai characters on the printer
- [ ] If the command add to pub.dev package was found
- [ ] Report here if it was achieved or not and close this

**Comment by tanlocle0495** [comment]
I think you need  convert text to bitmap.

**Comment by andresperezmelo** [comment]
Is right, not to be sending data to the printer in string right?
